### ISSUE TITLE
Binding to radio buttons

### ISSUE THREAD

**Issue by shipstar** [mikeric/rivets#32]
I think I'm just doing something wrong, but I'm having trouble binding to and from a radio button group. Given HTML like the following:

```
<input data-value="purchase.amount" name="amount" type="radio" value="500">$5</input>
<input data-value="purchase.amount" name="amount" type="radio" value="1000">$10</input>
<input data-value="purchase.amount" name="amount" type="radio" value="1500">$15</input>
<input data-value="purchase.amount" name="amount" type="radio" value="2000">$20</input>
```

the Purchase model's amount just gets set to "true" if any of the radio buttons are pressed and false otherwise. I've also tried data-checked, but it works the same way in this case.

I'd like to have a bidirectional relationship on radio buttons so that the correct input is selected based on amount, and the amount is updated based on selection.

Do you have an example that involves radio buttons? If you can get me started, I'll write it up and contribute it back to the README.

Thanks!

**Comment by wardtwits** [comment]
Is there still something wrong with Rivets input radio bindings?  I'm using ver 0.8.1 and my code shows and hides them if I use rv-show/ rv-hide, but using rv-checked and rv-unchecked is not functioning properly.

<input type="radio" name="radioGroup" rv-checked="model.isPrivate" value="private"> Private
<input type="radio" name="radioGroup" rv-unchecked="model.isPrivate" value="public"> Public

When isPrivate=false I see the public radio checked, but the private one is never correctly checked.  Again, I know the value is coming through correctly, because if I use hide and show they both correctly hide or show.

// test -- when isPrivate=true only the private radio button shows up
<input type="radio" name="radioGroup" rv-show="model.isPrivate" value="private"> Private
<input type="radio" name="radioGroup" rv-hide="model.isPrivate" value="public"> Public

Thanks!

**Comment by Duder-onomy** [comment]
@wardtwits Can you make a jsfiddle demonstrating your issue? Radio bindings work fine for me.

Remember that, rv-checked is only appropriate on the input type checkbox, not the radio. The checkbox is used to represent a boolean value on one property. 

Radio is used to represent a selected option, from many options, but only one.

Please paste a fiddle and I will help more.
