### ISSUE TITLE
using rv-attribute in the same element as rv-each

### ISSUE THREAD

**Issue by PierBover** [mikeric/rivets#468]
So I want to add an attribute in the repeated element but it does not work...

    <div rv-each-person="persons" rv-rel="{person.id}">{person.name}</div>

But the `rv-rel` is not parsed by Rivets.

Is this expected behaviour?

**Comment by PierBover** [comment]
I figured out that my code was wrong, but even when I corrected it rivets still doesn't parse it correctly. If it's on the repeated element.

This doesn't work
    <div rv-each-person="persons" rv-rel="person.id">{person.name}</div>

But this does
    <div rv-each-person="persons"><span rv-rel="person.id">{person.name}</span></div>

**Comment by Duder-onomy** [comment]
Can you make a jsfiddle where it is not working? 

Here is one I made that is working as close as possible (assuming allot) to your example. 
https://jsfiddle.net/erx5bqw0/

**Comment by PierBover** [comment]
Your example is not working. Check the attribute in the conde inspector

    <div rv-rel="person.id">one</div>

**Comment by Duder-onomy** [comment]
If you look at line number: 13 of the jsfiddle you will see that the `rv-rel` binder is defined but does nothing:

```javascript
rivets.binders.rel = function (el, value) {
    // do something here.
}
```

If you remove this and just bind that word `rel` to the element, with the `rv-*` binder,  you will see that everything works as expected as [evidenced here](https://jsfiddle.net/a76srpe8/).

Can you create a fiddle where it is not working so that we can help you?

**Comment by PierBover** [comment]
Whaddayaknow, I tried it again and now it works... I swear gremlins are real.

Thanks again for your help.
