### ISSUE TITLE
Is it possible to filter an array on rv-each?

### ISSUE THREAD

**Issue by PierBover** [mikeric/rivets#469]
Is it possible to order alphabetically, or only display a range of indexes ?

How?

**Comment by Duder-onomy** [comment]
Yes this is possible. There are many ways to do it. Here is a working fiddle demonstrating filtering the array with a formatter.  https://jsfiddle.net/c73o2tvx/

The important thing to note about the example, the formatter recieves the value from the input as an argument. Since the arguments to formatters are watched rivets will recomputed the formatter when the argument changes and when the list changes. 

You could easily change the formatter to accomplish alphabetical sort, or ony display a range. 
All you need to do is return the proper array from your formatter.

Does this help?

**Comment by PierBover** [comment]
Thanks!

Yes this helps :)

From the Rivets website I got the impression that formatters were a way to transform the text output. Is there some other website for learning Rivets?

**Comment by Duder-onomy** [comment]
yeah, unfortunately there is no other website for learning rivets. Though, I will say, the source code is readable once you figure out how it is all connected. 

I would be down to help with something like a learn rivets website. I want to find more ways to help @mikeric share the weight of this repo. 

Anyhow, glad it helps.

**Comment by PierBover** [comment]
How does this work exactly?

I mean, yes it filters an array. But how come the formatter is taking the array that `rv-each` uses instead of the value of each iteration?

**Comment by psibernetic** [comment]
That is because the property in the model you are pointing the rv-each binding to is an array. The elements that are children to the rv-each element will be per item.

**Comment by PierBover** [comment]
Thanks @psibernetic. The other piece I was missing is the use of Underscore.js (or so it seems).

    return _.filter(...

**Comment by psibernetic** [comment]
@PierBover Oh yes, got to love _.js. Also checkout the .where method, for simple filters it is such a joy.
