### ISSUE TITLE
rv-each updates only newly added rows in a list

### ISSUE THREAD

**Issue by pawelmurawski** [mikeric/rivets#480]
Check out this fiddle: https://jsfiddle.net/fsjvg0w5

After clicking "Add" button new row is added but "howmany" value is updated only for this new row, for every other it stays old. Is it an expected behaviour of RivetJS or is it a bug? If it is an expected behaviour then why it cannot work in a way when every row is updated when a model changes?

**Comment by Duder-onomy** [comment]
Here is your fiddle with the minimun number of changes it took to get it working like you said:
http://jsfiddle.net/rzdkq5xn/

I changed your bind call to bind an object with a property called state:

```javascript
rivets.bind($table, {state : state});
```

Then I access the properties `rows` and `howmany` from the state property on the bound object:

```html
<tr rv-each-row="state.rows" style="border: 1px solid black">

<td rv-text="state.howmany"></td>
```

**Comment by Duder-onomy** [comment]
BTW. I am not 100% sure why this happens, but I believe it is related to -  https://github.com/mikeric/rivets/issues/452 especially the findings of @tayfunyugruk

It seems like, when you incremented the `howmany` property, and it was the root property on the binding, that it replaced the reference to the property, so that each time you incremented it, it was a 'new' `howmany` property.

By putting the property on a object, then modifying that object the reference is maintained.

Hope this helps.

**Comment by pawelmurawski** [comment]
It works like a charm! Thank you for help.
