### ISSUE TITLE
Function Parameters

### ISSUE THREAD

**Issue by MatayoshiMariano** [mikeric/rivets#504]
Hi, I am new in the front-end, i am most an API guy.
So my question is how can I pass arguments to a function on the HTML.

Example
In my js I have:

```js
scope = {
  sum = function(a,b) { return a + b; }
}
rivets.bind($('body'), {scope: scope})
```
In the HTML

```HTML
<p>1 + 2 = {scope.sum(1,2)}</p>
```

How can I do this with rivers or I need some extra library?

Thanks!

**Comment by Leeds-eBooks** [comment]
I'm afraid it's not quite this simple. Rivets is not a convenience for embedding javascript in html – it is a data-binding library, for binding data models to your html. If you tell us your real use case, we might be able to suggest a Rivets way of doing it.

**Comment by MatayoshiMariano** [comment]
Hi Ben, thanks for answering. I am building a tiny dashboard where I compare my product's price with the price of the competence. Making a request by HTTP I get an array of products, and depending the price I return the CSS class name.

Any way of doing it?

**Comment by Leeds-eBooks** [comment]
So you don't actually need a sum function? What function were you hoping to evaluate?

**Comment by MatayoshiMariano** [comment]
It was an example, but I need something like this:

```js
difPercentage = function (price1 , price2) {
  (((price1 / price2) - 1) * 100).toFixed(2);
}
```

**Comment by Duder-onomy** [comment]
@MatayoshiMariano 
Here is a way to do something like what I think you were asking with formatters: https://jsfiddle.net/hp51xrpy/

---

To take your first example specifically:

```html
<p>1 + 2 = {scope.sum(1,2)}</p>
```

You can absolutely do something like this, but I am not sure why you would. 
You can do math etc in formatters. [Formatters are very cool](http://rivetsjs.com/docs/guide/#formatters)
You can chain them all day!

So you could write something like

```javascript
rivets.binders.sum = function(number1, number2) {
    return number1 + number2; // probably some null checking and some float parsing here.
}
```
```html
<p> 1 + 2 = { 1 | sum 2 }</p>
```

---

Rivets also lets you write these rad little things called binders. [Binders are super cool](http://rivetsjs.com/docs/guide/#binders)

With a binder and doing some math, it could look like this:

```javascript
rivets.binders.addToTheNumberOne = function(el, value) {  // This is a simple binder with a 'routine' function only. read the docs to get a grip on that.
    el.innerText = 1 + value;
}
```
```html
<p>1 + 2 = <span rv-addToTheNumberOne='2' ></span></p>
```

---

Both the above examples are probably not very useful though, because in Rivets you would probably want to bind to some property that will be changing, so as the numbers changed, the math would update. 

To touch on the formatter example, if you wanted all dynamic properties,  you would probably end up with something like. 
```html
<p>{ model.value1 } + { model.value2 } = { model.value1 | add model.value2 }</p>
```

---

Lastly, since you said you are new to Rivets. 
I think allot of people use formatters to simply change how a value is displayed. Binders are very useful when you need to do something to the DOM. I like to hide all my DOM manipulation behind binders, that way I can swap out the definition of the binding without touching the implementation. Since in a binder, you can get a handle on the `el` in which you bound to, it is a great place to stash jquery plugins and other crap like that. 

Something like, 
```html
<div rv-ace-editor='model.something'></div>
```
Would turn that div into an ACE editor and then I can count on the `model.something` to always be the current value of the editor. 

Anyhow, I hope you like Rivets. 
Please let us know if you need any help.

**Comment by Leeds-eBooks** [comment]
I remembered you said you want to set a className dependent on something. Could you use the `rv-class-[classname]` binder [like this](http://rivetsjs.com/docs/reference/#class-[classname])? You could do something like `<div rv-class-cheaper="product.ourPrice | isCheaperThan product.theirPrice">{product.ourPrice}</div>`. Your `isCheaperThan` formatter would compare with the `theirPrice` property on the product object. Obviously I'm making a million assumptions here...

**Comment by Leeds-eBooks** [comment]
@MatayoshiMariano closing this as I think you have got enough information. Please reopen if not!
