### ISSUE TITLE
rv-class="someting" and rv-class-other="somethingelse" work in specific order depending on browser

### ISSUE THREAD

**Issue by fsateler** [mikeric/rivets#508]
The following code:

    <div rv-class-category="isCategory" rv-class="theClass">One order</div>
    <div rv-class="theClass" rv-class-category="isCategory">The other order</div>

Will not render correctly in chrome or firefox (it does in ie, though). Chrome only displays correctly the second version while firefox picks up the first version.

See this fiddle for an example (I tried it with chrome, firefox and ie) https://jsfiddle.net/fqycqsu6/

**Comment by Duder-onomy** [comment]
This is related to: https://github.com/mikeric/rivets/issues/409

This issue was solved by giving the typical order dependent binders a 'priority': 
The checked binder for example runs at level 2000 : [source](https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L32)
The value binder runs at level 3000 : [source](https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L71)

Please read through the issue I referenced. Let us know what you think.

I don't think that attribute order is guaranteed in all browsers. So simply running them in the order they are found is not enough to fix your issue. That is why the 'binder priority' solution was implemented.

Mr. Mike is currently re-writing this lib and if you have some super awesome clever bullet proof monk idea to solve this. The time is nigh.

**Comment by fsateler** [comment]
Hi @Duder-onomy 

Your code references pointed me in the right direction: the problem is that there is not a specific handler for the class attribute, and it uses the generic one that overwrites the attribute value. The rv-class-* binder, on the other hand, does append the class. Combine this with the nondeterministic attribute order and you explain the observed behavior. 

I think the normal expectation is that `rv-class` adds a class instead of setting the class attribute to exactly that. If I'm wrong, then a rv-appendclass or something like that should be added.

**Comment by Duder-onomy** [comment]
Here is a 'append-class' binder for you: http://jsfiddle.net/komrqk4g/

Roughly based on the one here: https://github.com/mikeric/rivets/wiki/Custom-Binders#addclass

The pertinent bits:

```javascript
rivets.binders['append-class'] = function(el, classToAppend) {
    if(el.addedClass) {
        el.classList.remove(classToAppend);
        el.addedClass = null;
    }
    
    if(classToAppend) {
        el.classList.add(classToAppend);      
        el.addedClass = classToAppend;
    }
};
```

``` html
<div rv-append-class='model.someClass'></div>
```

I will take note of your comment about the behavior of the 'rv-class' binder.  If some other people have this same issue we will be sure to bring it up again / add this to the documentation.

Please let us know if this helps you. If it does. Please close this issue as we are trying to clean up the old issues.

**Comment by fsateler** [comment]
That code is not safe to use multiple times, as one call will remove the class added by the other one.

I used:

        appendclass: function (el, value) {
            el.classList.append(value);
        }


I think this can be closed, although documentation about this would still be nice.

**Comment by Duder-onomy** [comment]
Rawk. Noted about the append-class binder, thats what I get for drinking in the morning.
