### ISSUE TITLE
NOT operator for binders

### ISSUE THREAD

**Issue by dave-islive** [mikeric/rivets#517]
Would it be possible to add a NOT operator to binders like rv-class-*, at the moment I include a not* property in the object to use rv-class-* correctly when a certain property is set to false

**Comment by Leeds-eBooks** [comment]
I just use a "not" formatter – this is exactly the kind of thing formatters are intended for.

```html
<div rv-class-highlighted="someValue | not"></div>
```

```javascript
rivets.formatters.not = val => !val
```

**Comment by Duder-onomy** [comment]
This one is pretty cool. I just made it now, so maybe don't use in production. But could be some inspiration for you?

You can make a `rv-not-*` binder to negate the value going into all other binders.  This implementation pasted will not work with the `class-*` binder because there would need to be some additional checking around the binders with wildcards. 

```javascript
rivets.binders['not-*'] = {
    bind : function(el) {
        var binder = rivets.binders[this.args[0]]; 
         
        if(binder instanceof Function) {
            this.binder.routine = function(el, value) {
  	        	return binder(el, !value);
            };
        } else {
        	this.binder.routine = function(el, value) {
                return binder.routine.call(this, el, !value);       
            }.bind(this);
            
            this.binder.unbind = binder.unbind;
            
            binder.bind.call(this, el);
        }
    }
};
```

Use it like :
```html
<div rv-not-if='model.value'>YEAH YEAH YEAH</div>
```

Here is a working [fiddle](http://jsfiddle.net/mk5hvpwt/)

Please close this issue if your problem is solved.

**Comment by dave-islive** [comment]
Thanks for the answers, these 2 options will probably accommodate any type of use.
