### ISSUE TITLE
issue with collection.remove(model) rendering with rv-each-model='...

### ISSUE THREAD

**Issue by levieraf** [mikeric/rivets#521]
Hi guys,

I have:
```javascript
var collection = new App.Collections.Notes();
var data = [
    {id: 1, description: 'description short 1', removed: 0},
    {id: 2, description: 'description short 2', removed: 0},
    {id: 3, description: 'description short 3', removed: 0},
    {id: 4, description: 'description short 4', removed: 0},
    {id: 5, description: 'description short 5', removed: 0},
    {id: 6, description: 'description short 6', removed: 0},
    {id: 7, description: 'description short 7', removed: 0},
    {id: 8, description: 'description short 8', removed: 0},
    {id: 9, description: 'description short 9', removed: 0},
    {id: 10, description: 'description short 10', removed: 0}
];


var view = new App.Views.Applications.Test({
    collection: collection
});
Helpers.htmlView(view, '.body');
collection.reset(data);
```
The template:

```
<table class='table table-hover'>
	<tbody>
		<tr rv-each-modelRow='collection.models' rv-class-hidden='modelRow.isNotRemoved < :removed'>
			<td>
				<a href="javascript:void(0);" class="btnRemove" rv-data-id='modelRow:id'>Remove</a>
			</td>
			<td>{modelRow:id}</td>
			<td>{modelRow:description}</td>
		</tr>
	</tbody>
</table>
```

Within the view I have an action to remove the model clicked, is this:
```javascript
	removeRow: function (e) {
		var element = $(e.currentTarget),
			id = element.data('id'),
			model = this.collection.get(id);
		this.collection.remove(model);
	},
```

Now, if I remove the first one row, work perfect, this removes the model from the collection, but I click the second one row to remove, even after has been removed the first one from the dom and collection, this continue thinking that the first one is there. but it is not true.

Any idea?

someone with same issue before?

**Comment by b44rd** [comment]
I've experienced the same, but haven't figured out why. The behaviour works the first time, but next time, it fails. However, if using rv-on-click="removeRow" on the removal link instead (which is the preferred approach), it will work the way you want. The removal function will typically look something like this: 

```javascript
removeRow: function (e, model) {
  // Do whatever you want to the model here
}
```

**Comment by Duder-onomy** [comment]
@levieraf Can you show us what Adapter you are using? Backbone `collection.remove` will trigger the `update` event on the backbone collection. Does your adapter listen for the backbone collection `update` event?

Backbone JS Source: http://backbonejs.org/docs/backbone.html#section-110

**Comment by levieraf** [comment]
@Duder-onomy did you mean this:
```
  window.rivets.adapters[':'] = {
      observe: function(obj, keypath, callback) {
          obj.on('change:' + keypath, callback);
      },
      unobserve: function(obj, keypath, callback) {
          obj.off('change:' + keypath, callback);
      },
      get: function(obj, keypath) {
          return obj.get(keypath);
      },
      set: function(obj, keypath, value) {
          obj.set(keypath, value);
      }
  };
```

I did the test with the code above below, I also did test with:

https://github.com/azproduction/rivets-backbone-adapter

But without successful. :(

**Comment by Duder-onomy** [comment]
Yes, Backbone and Rivets. So cool. 

Your ':' adapter only accounts for backbone models. You will need to make it a little more complete if you want to use backbone collections. 

If you want to use backbone collections with rivets, you will need to add something like the following: 

```javascript
observe : function (model, keypath, callback) {
    if (model instanceof Backbone.Collection) {
        model.on('add remove reset change update', function (obj, keypath) {
            callback(obj.get(keypath));
        });
    } else if (model instanceof Backbone.Model) {
        model.on('change', function () {
            callback(model.get(keypath));
        });
    }
},

unobserve : function (model, keypath) {
    if (typeof (model) == 'undefined') {
        return;
    }
    if (model instanceof Backbone.Collection) {
        model.off('add remove reset change');
    } else if (model.off) {
        model.off('change:' + keypath);
    }
},

get : function (model, keypath) {
    if(model instanceof Backbone.Collection) {
        return model.models;
    }
    return model.get(keypath);
},

set : function (model, keypath, value) {
    if (model instanceof Backbone.Model) {
        model.set(keypath, value);
    }
}                

```

This has some caveats, but these are backbones caveats not rivets, 
for example, you cannot do:
```html
<div rv-text='model:something.nested'></div>
```
As this would be using both the dot and colon adapters, it would use the colon adapter to get the `something` from the model, then use the dot adapter to get the `nested` from the something. 

This will work the first time but it will not be watched. 

You will need to implement some kind of nested getters and setters to backbone so that you can do something a little more sophisticated. 

Where I work, we have a backbone SPA library called [masseuse](https://github.com/Solid-Interactive/masseuse)  It works pretty well and has exampled (and tests) for all of rivets functionality working seamless with backbone models. The only caveat and if you look at our rivets [adapter](https://github.com/Solid-Interactive/masseuse/blob/master/app/plugins/rivets/adapters.js) you will see why it is weird. But to get nested models and properties and to be observed by rivets, when they are on a backbone model, we first trick rivets into thinking the entire keypath is a string:
```html
<div rv-text='model:something->nested->nestedagain'></div>
```
This passes the string 'something->nested->nestedagain' to the rivets adapter, we then replace the `->` with a `.` and use our backbone deep getters and setters. This basically tricks rivets into only observing the root property, in this case `model` and then backbone deep getters and setters will broadcast change events all the way to the root model. 

Also, if you are using a collection to each over with rivets, 
```html
<ul>
    <li rv-each-item='model.collection'></li>
</ul>
```
This would return the collection to the iterator, but as we all know, a backbone collection is not an array. a backbone collection has a `models` property on it that contains the models, so, you will need to do something like this (notice the trailing colon)
```html
<ul>
    <li rv-each-item='model.collection:'></li>
</ul>
```

I know this all seems weird, but once you get it working how you want it to, rivets + backbone is really really really cool. Unfortunately it does not work out of the box perfectly, but everything can be overcome and rivets will win! This is gonna bite me in the ass for saying it, but I think the best way to roll is to become very familiar with the source code of the libraries you chose to use.

Please let me know if there is anything else I can help with. If the repo you are working on is open source, I can go take a look let you know. 

If this solves the issue, Please close.

**Comment by levieraf** [comment]
@Duder-onomy hey man thanks! after to add your adapter the other step was change at rv-click='remove' and then inside the function view:

View:
```
	remove: function () {
		this.collection.remove(this.model);
	} 
```

Template:
```
<table class='table'>
	<tbody>
		<tr helper-each-model='collection.models'>
			<td>
				{model:id}
			</td>
			<td><a href="javascript:void(0);" class='btn-remove' helper-on-click='remove' helper-data-id='model:id'>Remove</a></td>
		</tr>
	</tbody>
</table>
```

I will check your adapter and apply any gets better to solve the issue that you mean.


Thanks man!
