### ISSUE TITLE
Force a formatter read after publish

### ISSUE THREAD

**Issue by Boycce** [mikeric/rivets#524]
Changing an input from `40.00` to `40.000` doesn't trigger the formatter `read` function due to the binded object not changing:
```
rivets.formatters.currency = {
  read: function(value) {
    return (value / 100).toFixed(2);
  },
  publish: function(value) {
    return parseFloat(value) * 100;
  }
};
```
How to force a `read` after a `publish`?

**Comment by Duder-onomy** [comment]
Hi, 
Can we see a non working fiddle? 

You should not need to force a read or publish if the bound value has changed. If the bound value changes and the formatter does not recompute, then I believe there is an issue in your binder. 

What you will probably want to do instead of calling `read` or `publish` directly, is to fire a `input` event on the input. 
If you are using the `rv-value` binder, [that binder listens for the `input` event](https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L75). Is it possible that you are using some jquery plugin or something like that? I have found that many jquery plugins do not follow the spec and fire the proper events on inputs. 
Anyways, you will probably want to do something like, 

```javascript
// not real code.
inputElement.trigger('input');
```
This will trigger the appropriate handlers in rivets to publish the value to the model, and run all formatters. 

Please let us know if this helps you.

**Comment by Boycce** [comment]
Hey @Duder-onomy. Publishing  both `parseFloat( 40.00 or 40.000 ) * 100` returns `4000`.
Therefore it was an adapter problem with the backbone setter. I finally got it working, forcing a `set` change event.
```
rivets.adapters[':'] = {
  //...
  set: function(obj, keypath, value) {
    obj.set(keypath, value, {silent: true});
    obj.trigger('change:' + keypath);
  }
};
```

**Comment by Duder-onomy** [comment]
Awesome!
