### ISSUE TITLE
rv-value overrides "value" attribue of a radio button

### ISSUE THREAD

**Issue by tpepio** [mikeric/rivets#528]
Not sure if this is an issue (quite new to rivets),

I found this using rivets v0.6.9 (http://jsfiddle.net/#&togetherjs=Kkbvn4R3zg)

But I was unable to reproduce it with v0.8.0 because i get the following error "rivets is not defined"
(http://jsfiddle.net/#&togetherjs=Kkbvn4R3zg)

Here's the sample I used for my tests :

```
<!DOCTYPE html>
<html>
<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://rawgit.com/mikeric/rivets/v0.8.0/dist/rivets.min.js"></script>
	<meta charset="utf-8">
</head>
<body>
	<section id="test">
		<h3 rv-text="test.enabled"></h3>
		<input type="radio" name="enabledOrDisabled" rv-value="test.enabled" value="enabled">Enabled</input>
		<input type="radio" name="enabledOrDisabled" rv-value="test.enabled" value="disabled">Disabled</input>
	</section>
	<script>
	console.clear();
	var testModel = {enabled: 'enabled'};
	
	rivets.bind($('#test'), {
	  test: testModel
	});
	</script>
</body>
</html>
```

Thomas.

**Comment by Duder-onomy** [comment]
Hi Thomas, 

The keypath engine used by rivets was split into its own repo. So, if you are going to use rawgit to serve the files, you will need to use the [bundled version](https://github.com/mikeric/rivets/blob/master/dist/rivets.bundled.min.js) of rivets and not the stand alone minified version. Looking at the [`dist` directory](https://github.com/mikeric/rivets/tree/master/dist) you should be able to see the 3 diff versions. 

Your rawgit script tag for rivets should look like: `https://rawgit.com/mikeric/rivets/master/dist/rivets.bundled.min.js`

Please let me know if this helps. I would have updated your jsfiddle, but there was no content in the fiddle.

**Comment by tpepio** [comment]
Hi and thank you for your help !

I updated the reference to rivets in my sample with the bundled one, and managed to make a proper jsfiddle example this time ! Here it is : https://jsfiddle.net/qxztdLk0/

When I use ```rv-value``` on radio inputs, their default ```value``` attribute gets overridden. Is that the correct behaviour ?


Thanks,
Thomas.

**Comment by Duder-onomy** [comment]
Hi Thomas, 
You would need to use the `rv-checked` binder with radio inputs. 
Your updated fiddle: https://jsfiddle.net/cqebn38c/

If you look in rivets source, https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L32
You should see the `rv-checked` binders definition. 
If you look at this binders routine function, there is a check for the type of input, if the input type is a radio, then rivets will set the value of the bound option to the value of the value attribute on the input.
I only say these things so that you might get used to looking at the source and making your own binders (and thus rivets will unveil its inner workings to you and become the One Ring to your Sauron)

Please close if this helps you. 
Greg

**Comment by tpepio** [comment]
Thanks a lot for your help ! Looking at the source helps indeed.

Closing the thread as this is not an issue.
