### ISSUE TITLE
Suggestion for client-side template extension / inheritance?

### ISSUE THREAD

**Issue by jiaweihli** [mikeric/rivets#531]
This is a bit off-topic, but do you have any suggestions for a templating library that's also as agnostic as rivets?  (and plays well with it?)  Or, barring that, do you have any warnings against popular templating library choices?  No need to explain very in-depth, I know your time is valuable!

**Comment by Duder-onomy** [comment]
Client or Server templating? 

If client templating, do the templates need to be alive? dual binding?

**Comment by jiaweihli** [comment]
Client-side templates.  I only need one-way binding from model to template (which is taken care of by rivets) - I handle template to model changes through event handlers.

**Comment by Duder-onomy** [comment]
Where I work, everyone likes using jade on the client side. Jade is allot like haml, it makes HTML easy to read and makes the mental parsing of bindings pretty trivial. Jade also gives you mixins and other fancy stuff to cut up your html. This is easy to do on client with either [require.js](https://github.com/deedubs/require-jade) or [browserify](https://github.com/domenic/jadeify) to transform `.jade` files into functions that can be called with the model to template. We have used underscore templates in the past because we had underscore as a dependency anyways (backbone). 

We also use Riot.js allot, This is really awesome for templating (though it does allot more than just that).

Just my opinions. Curious as to what everyone else is doing?

**Comment by jiaweihli** [comment]
Interesting.  We've been using underscore templates for simplicity so far, but we're starting to see a lot of duplication from subclassing views.
