### ISSUE TITLE
Rebinding model to template in iFrame fails after reload

### ISSUE THREAD

**Issue by weltwinkel** [mikeric/rivets#599]
I have an index.html where I create my data models. These are updated using websockets during the entire session.

A client can open a "panel" in an iframe to display certain information. While the panel is open, the models are bound to a template in the panel and automatically updated - which works great!

While closing/reloading the panel in the iframe, I am unsuccessfull in unbinding the models from the template and removing all the helper methods added during the binding process.

When I open the panel again, I can bind the models to the template again, my main problem is that the view isn't automatically updated any more.

This is part of my panel.html code so far:

`var modules = window.parent.modules; // get modules-array generated in index.html
var template;

$(function(){ // panel was opened -> bind models to template
    template = rivets.bind($("#modules"),{ modlist :  modules });
});

$(window).on('unload', function(){ // panel is closing -> unbind models!
    template.unbind();
});`

The corresponding template:

`<div id="modules"><div rv-each-module="modlist">
        <span>{ module.id }</span>
        <span>{ module.state }</span>
        <span>{ module.template }</span>
    <div>
</div>`

Any insight is very much appreciated!

**Comment by jccazeaux** [comment]
This could be a consequence of issue #590 
When your model is bound, default adapter adds getter and setter. When unbound these getters and setters are not removed. When bound again, default adapter ignores all of your models because there is already getters and setters.

**Comment by weltwinkel** [comment]
Thanks @jccazeaux, I've noticed that. Is there any solution to this issue?

**Comment by blikblum** [comment]
You must reset the template after unbind. See http://codepen.io/blikblum/pen/eJGxRg

**Comment by weltwinkel** [comment]
Thanks for the link @blikblum! This plunker illustrates my problem better: http://plnkr.co/DYPDBeIRhtSifES2k9jn

Clicking: 
- bind
- update 
- unbind
- bind
- update = works!

Clicking:
- bind
- update
- unbind
- reload iframe
- bind
- update
= doesn't work!

Any ideas as to why?

**Comment by jccazeaux** [comment]
Yes I know why. You have two JS contexts : the parent and the iframe.
* Your model is in parent's context
* Your rivets instance is in iframe's context

When you bind your model, rivets adds getters and setters on each observed object. These functions are defined to work on rivets instances (with the closures).
Getters and setters are bound only at first bind. They are made to work on rivets instance that created them.
When you refresh your iframe, you create a new rivets instance. When trying to bind, rivets will not recreate getters and setters because they already exist. It will only push new callbacks. But these callbacks are store on current rivets instance, not on the first instance that created getters and setters.

The solution : model and rivets must be on same JS context. So use parent's rivets
```Javascript
window.parent.rivets.bind(...)
```

See solution here : http://plnkr.co/NsSn8ciyucsk5Roo8TEi

**Comment by weltwinkel** [comment]
Of course! Thanks @jccazeaux , should have thought of that!
