### ISSUE TITLE
The content of binded element are visible on page load

### ISSUE THREAD

**Issue by dnadeau-quatral** [mikeric/rivets#607]
### Bug description
When I reload the page, I can see the content of the element before the substitution occurs.
Look at the gif for more details.

I"m using the iterator binding
```html    
<div id="binded">
    <ul>
        <li rv-each-todo="list.todos">
            <span>{ todo.title }</span>
        </li>
    </ul>
</div>
```
```javascript
var list = {
    todos: [
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'},
        {title: 'Task #1'}
    ]
};
jQuery(document).ready(function () {
    rivets.bind($('#binded'), {list: list});
});
```
### Gif
![006c5453c36430553969293a076eecf3](https://cloud.githubusercontent.com/assets/4106750/14053563/7b0151e6-f2a8-11e5-8b40-1c80f7e98a6d.gif)

You can see the `{ todo.title }` before content is replaced. I do something wrong ?

**Comment by Duder-onomy** [comment]
Hi, Yes, you are doing everything correct. It is expected that a binding which takes some time to run will also take some time to render. Especially if you are putting your dependency imports at the bottom of the body. This is pretty simple to overcome. 

In rivets, you can define binders for most anything, here is an example of an `rv-cloak` binder: (if you are familiar with angular you will be used to using something like this to prevent the exact same issue.)

```javascript
rivets.binders.cloak = {
    priority : -1000,
    bind : function(el) {
        el.style.opacity = 1;
    }
}
```

I could not reproduce the [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) in jsfiddle...I think they have code preventing it. So here is a link to a [gist](https://gist.github.com/Duder-onomy/43f580b65578a102ec05#file-rv-cloak-html) I made to repro your issue. Just open it up in your browser to see the results. Instead of 12 todos, I made 10,000. 


This important bits about the `rv-cloak` binder. 

- The binder priority is set to negative one thousand. The priority attribute on binders will influence the order in which binders fire. If you look [here](https://github.com/mikeric/rivets/blob/master/src/binders.coffee), you will see that some of the built in binders use this. This order of binders firing is important to your domain and we cannot guarantee the order that element attributes will show up in the browser (not always the order you put them in your html). A high priority will ensure it fires first, and a low priority ensures that it will fire last. So, if we use a negative one thousand priority, we are ensuring that this is the last binding to fire. 
- In the `rv-cloak` binder I made, I am setting the opacity of the element to 1. This can really be anything you choose. You can use it to maybe a hide a spinner, or set the display to something. You should use that bit and a little fancy design to ensure that it looks good. In my example a little css is also necessary to initially hide everything in the DOM with a `rv-cloak` attribute:
    ```css
   [rv-cloak] {
        opacity: 0;
        transition: opacity 0.5s ease;
    }
   ```
- It is important that the `rv-cloak` binder be invoked on the parent element of a `rv-each`. I recommend using it all the time and putting it at the top of every rivets view you create. This will ensure that rivets is done with everything it needs to do before showing your content.

Please let us know if this helps you! 
If this solves it for you, please close the issue.

**Comment by dnadeau-quatral** [comment]
Nice details ! Thanks a lot, I'm happy with the result !
