### ISSUE TITLE
How to get adapter from a customer binder (documentation is wrong)

### ISSUE THREAD

**Issue by whitingj** [mikeric/rivets#640]
I'm trying to get the adapter in my custom binder.  However I'm unsure how to do this.  The example from the documentation does NOT work.  `adapter = this.config.adapters[this.key.interface]` doesn't give you the adapter as this.config is undefined and this.key is undefined as well.

So how am I supposed to get the adapter?

```
rivets.binders.toggle = {
  bind: function(el) {
    adapter = this.config.adapters[this.key.interface]
    model = this.model
    keypath = this.keypath

    this.callback = function() {
      value = adapter.read(model, keypath)
      adapter.publish(model, keypath, !value)
    }

    $(el).on('click', this.callback)
  },

  unbind: function(el) {
    $(el).off('click', this.callback)
  },

  routine: function(el, value) {
    $(el)[value ? 'addClass' : 'removeClass']('enabled')
  }
}
```

**Comment by mkastner** [comment]
Not sure, if this helps, but your problem seems to be similar to the one I had. Basically, in simple cases, you don't need an adapter. Just using the observer directly already does the job:

[https://github.com/mikeric/rivets/issues/634](https://github.com/mikeric/rivets/issues/634)

In particular this fiddle:

[https://jsfiddle.net/bu4844dd/8/](https://jsfiddle.net/bu4844dd/8/)

**Comment by Leeds-eBooks** [comment]
I will close this once https://github.com/mikeric/rivets/pull/648 is merged.
