### ISSUE TITLE
Incompatible with ender js 

### ISSUE THREAD

**Issue by carnage** [mikeric/rivets#646]
When used with Ender Js, there is an error on load. It is due to ender registering the $ function which is being detected in https://github.com/mikeric/rivets/blob/master/src/util.coffee 

Several options for a fix.

You could prevent the usage of jquery bindings if the ender function is defined 

You could use $ to bind the methods instead of jQuery

or You could use (window['jQuery'] || window['$']) to create your methods, matching the if statement.

**Comment by Duder-onomy** [comment]
Yeah, you are totally right. I just read through the 'ender.js' docs and it seems there is no way to release control of the `$`.  Considering jQuery has been around for 10 years ish, and 'ender.js' for less, seems like ender should have accounted for the `$` being in such high demand. Have you also opened up an issue on 'ender.js' so that they will make their shorthand lib reference something that does not conflict with jQuery?

Rivets was written in 2012, and I am sure that at the time, the `$` was probably only in demand from jQuery, at that time there would have been little reason to assume some other library wanted to use it.

Anyways, you are correct that there should be a way to opt out of this auto detect jQuery behavior as other libs will eventually want control of the `$` as well.  

If we were able to make this jQuery or no jQuery business a little better I think we could also resolve this issue: https://github.com/mikeric/rivets/issues/641 

I think some of the other core members should comment here and gauge interest.

**Comment by carnage** [comment]
Ender.js is intended to be a lightweight jQuery replacement; the code in rivets works fine if it uses the $ function provided by ender, the issue is it looks for $ || jQuery then uses jQuery

**Comment by blikblum** [comment]
Why not always use addEventListener?

**Comment by jccazeaux** [comment]
See my comment [here](https://github.com/mikeric/rivets/issues/641#issuecomment-237236837). May be it can help you?

**Comment by Namek** [comment]
I use http://minifiedjs.com/ and sometimes (rarely) rivets can't initialize because `jQuery is undefined`. Of course minifiedjs also initializes global `$` because it's meant to replace jQuery lib.

As @carnage explained it checks for `$` OR `jQuery` and then always try to use `jQuery`.

**Comment by Namek** [comment]
@Duder-onomy wouldn't it make sense to merge #679 until next decisions about jQuery are made?
