### ISSUE TITLE
Two way formatters don't execute keypath on parameters for publish function

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/rivets#649]
In two-way formatters we define two functions `read` and `publish`. `read` works fine and receives parameters. But `publish` function receives as parameters the keypath instead of the observed value.
See it [in this fiddle](https://jsfiddle.net/jccazeaux/04d72ce3/)
I defined a two-way formatter called with two parameters

In the console you will see
```
read arg1 Hello
read arg2 Mr
publish arg1 'Hello'
publish arg2 scope.prefix
```

**Comment by Leeds-eBooks** [comment]
Nice, I have found this bug in the past but just worked around it. I think the bug comes from [this line](https://github.com/mikeric/rivets/blob/master/src/bindings.coffee#L112), where rivets is just getting the formatter arguments as strings direct from the template, rather than processing them into values as it does [here](https://github.com/mikeric/rivets/blob/master/src/bindings.coffee#L52).

**Comment by Leeds-eBooks** [comment]
@jccazeaux I've just written a failing test for this (also verifying that I can make the test pass by testing for the formatter argument strings rather than their resolved values). I will commit this test to master now.
