### ISSUE TITLE
Bug in binding in a very specific configuration

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/rivets#650]
I have a very very specific bug that occurs only when you have
* A binder `rv-if` with some condition
* A binder `rv-each` on an array inside the `rv-if`
* Inside the `rv-each` display array length
[Full exemple here](https://jsfiddle.net/jccazeaux/fb8pw2xL/)

The bug happens when you
1. Add data to the array (in reality it's a ajax request that adds data)
2. Toggle the `rv-if` condition to remove the element (in reality the condition is on the length of the array)
3. Reset the array
4. Toggle the `rv-if`
5. Try to add data...won't work

To get it to work again i must toggle the `rv-if` twice.

**Comment by blikblum** [comment]
I managed to find why:

- The each binder will create a observer at `scope.pages`
- Adding a item, the each binder will create a child view that will reuse the `scope.pages` observer because of `{scope.pages | length}`
- Toggling if binder off will unbind the each bindings and will delete the `scope.pages` observer
- Resetting pages will create a new non observed `scope.pages` property
- When if bind toggled on the each binder will create a new observer at `scope.pages`
- When each binder routine is called the child view will be unbind because collection length is different from iterated length -> this will delete the `scope.pages` observer and reactivity is lost

**Comment by blikblum** [comment]
If instead of reseting the array, remove one of the item the same bug occurs

**Comment by jccazeaux** [comment]
Nice, that's a good explanation. Do you see a solution?

**Comment by blikblum** [comment]
For this specific case yes, but will be symptomatic. The root issue lays deeper.

See http://codepen.io/blikblum/pen/OXBarY

Add some items
Toggle if
Try add more items

**Comment by jccazeaux** [comment]
I agree, the cause is deep, maybe in the adapter's observce/unobserve functions.
We have many examples, this will make it easier to fix and test!

**Comment by jccazeaux** [comment]
The issue may be in adapter. See http://codepen.io/jccazeaux/pen/WxaPdm
When no adapter is used in expressions, there is no issue.

**Comment by blikblum** [comment]
I already fixed in my side. Just need a test

**Comment by jccazeaux** [comment]
I think i'm close
See here : https://github.com/mikeric/rivets/blob/master/src/adapter.coffee#L97
When `unobserve` is called on array's keypath, the mutation observers (push, slice...) are deleted regardless of the other observers.

**Comment by jccazeaux** [comment]
😄 
I have a test, i send a PR with it right now

**Comment by jccazeaux** [comment]
My working fix is to replace
```javascript
          unless callbacks.length
            delete map.callbacks[keypath]
          
         @unobserveMutations obj[keypath], obj[@id], keypath
```
with
```javascript
          unless callbacks.length
            delete map.callbacks[keypath]
            @unobserveMutations obj[keypath], obj[@id], keypath
```
It will unobserve mutations only when there are no callbacks left. You have the same?

**Comment by blikblum** [comment]
The same

**Comment by jccazeaux** [comment]
Great, i add it to the PR
