### ISSUE TITLE
Order of operations matters when using computed properties and a formatter

### ISSUE THREAD

**Issue by goose2460** [mikeric/rivets#658]
Specifying the computed property dependency before a number formatter and the `| call` results in the property not being recomputed

https://jsfiddle.net/64ta6qzz/18/

**Comment by jccazeaux** [comment]
The idea of `call` formatter is to send arguments to function. The function will work with the arguements instead of getting the data in the model. With arguments Rivets will be able to bind all necessary data. You won't have to use the `computed properties` notation.
In your example this will be
https://jsfiddle.net/jccazeaux/j1dqe2d9/1/

**Comment by jccazeaux** [comment]
In fact, the only usage of `computed properties` is
`state.remainingTime < state.currentTime | call | formatter`
In the following expression
`state.remainingTime | call | formatter < state.currentTime` 
`<` and `state.currentTime` are handled as parameters for the `formatter`, not as computed properties. So it works because when `state.currentTime` changes, rivets will reexecute the expression.
In the correct notation in fact it works, but since `0.9` functions are not executed so when reevaluating the `state.remaingTime` it will return the same function as a pointer. The dataBinding won't be executed because the value (pointer on function) has not changed. See #572 it's the same problem here.
The good news is, when PR https://github.com/mikeric/sightglass/pull/16 is merged, the bug will be fixed !

**Comment by Leeds-eBooks** [comment]
@jccazeaux https://github.com/mikeric/sightglass/pull/16 is merged, but I'm not sure how to release.

**Comment by Leeds-eBooks** [comment]
Should we change the docs on **computed properties** to make it clear that it doesn't need to be used if you are using `| call`?

**Comment by jccazeaux** [comment]
To release sightglass it must be pushed in npm as a `0.2.6`. Then in rivets' `package.json` just reference this `0.2.6` before the build.
Yes the doc must be updated, i'll handle it with `0.9.2` update

**Comment by Leeds-eBooks** [comment]
It is also on bower and component – shall we just ignore them?

**Comment by jccazeaux** [comment]
We should keep the version up to date in all the repo. Is sightglass really used outside rivets?

**Comment by Leeds-eBooks** [comment]
I use it outside rivets 😛

**Comment by jccazeaux** [comment]
@Leeds-eBooks has sightglass been published?

**Comment by Leeds-eBooks** [comment]
No, will do it asap

**Comment by jccazeaux** [comment]
OK, package.json must be updated to use it for the `rivets.bundle.min.js`?

**Comment by Leeds-eBooks** [comment]
Yeah I guess I'll have to publish `0.9.4` after I've released sightglass?

**Comment by Leeds-eBooks** [comment]
Ah, totally didn't know that bower fetches the latest version from github automatically!

**Comment by Leeds-eBooks** [comment]
Ok updated sightglass is bundled in `0.9.4`
