### ISSUE TITLE
master-details pattern

### ISSUE THREAD

**Issue by erdalkaraca** [mikeric/rivets#671]
Does rivets have support for the master-details pattern?
If not, how would you implement this using a new binder?

**Comment by jccazeaux** [comment]
Master details can be done without new binder. Just use the `args` formatter described in #672 
Here is a full example https://jsfiddle.net/jccazeaux/sn584fn5/

**Comment by Duder-onomy** [comment]
@jccazeaux That is dope. Never thought of an `args` formatter before. 

@erdalkaraca 

Here is my 5 minute version of the master details pattern done in rivets: https://jsfiddle.net/Vornagreg/Lmky5hg1/1/

Off the top of my head I can think of 3 diff ways to do this with rivets. Thats why rivets is so damn cool. You can fit the library to match the pattern of your domain.  

Let us know if this makes sense or you need additional help! Otherwise, please close this sucker!

**Comment by erdalkaraca** [comment]
That is exactly what I was looking for!
Thanks to you both for your precious time!
