### ISSUE TITLE
parameterize on-* event handler calls

### ISSUE THREAD

**Issue by erdalkaraca** [mikeric/rivets#672]
Is it possible to parameterize the on-* event handler calls?

For example:

```
<input rv-value="my.object.name" rv-on-change="saveObject | my.object">
<input rv-value="my.object2.name" rv-on-change="saveObject | my.object2">
```

Here, I would like to pass the bound object (my.object) to the saveObject function call.
At the moment, rivets will provide the jquery event and the model from the binding.

Thanks.

**Comment by Duder-onomy** [comment]
If you are trying to make that 'saveObject' call be super generic in that it will just save the object bound to it, I would recommend making a custom binding. This would let you do something even more elegant than having an `rv-value` and a `rv-change`  You could make a `rv-save-on-change` binding that would just save the object during its `publish` cycle. Let me know if you need a hand with that and I can whip up an example one real quick.

Usually when I implement something like this in Rivets, I have a handle on the bound model so I can just access the property from it. If you are inside a loop, the iterated property will be available on the context as the alias you gave it when you invoked `rv-each-[alias]`

A nice trick is to configure the handler for any function calls so that the `this` or scope of the function call is the bound view. 

```javascript
Rivets.configure({
    // This fires when you use rv-on-*
    handler : function(context, ev, binding) {
    // https://github.com/mikeric/rivets/pull/275#issuecomment-36464555
    // http://jsfiddle.net/t2sxB/2/
    this.call(binding.observer.target, ev, binding.view.models);
}
```

This will ensure you can do something like:
```html
<input rv-value='view.model.thing' rv-on-change='view.handleInputChange'>
```
```javascript
var view = {
    model : {
        thing : 'Duder'
    },
    handleInputChange : function(event, context) {
        //in here this === view
        _saveToServer(this.model.thing);
    }
};
```

---

The Most similar thing I can think of that will achieve what you want above is to use the 'call' formatter and a non existing binding. 

Some history:
If you pass an argument to a formatter, that formatting chain will be re-evaluated when subscribed arguments change. If the leading property on that chain is a function, that function will be called. 

If you look at this fiddle: https://jsfiddle.net/Vornagreg/81hj1m00/

You can see that there is a `saveObject` function being called every time the object changes. 

The pertinent bits: 

```html
<input rv-value="view.model.object.name" rv-save-on-change="view.saveObject | call view.model.object.name">
```

Notice that the 'view.saveObject' has a subscription using the `call` formatter and the argument being the `view.model.object.name`. This will call that original function when the end property changes.

**Comment by jccazeaux** [comment]
We could use a formatter very similar to `call`. I would call this formatter `args`. `call` executes a function with arguments, `arg` would only return a function with arguments but will not execute it.

The formatter will be
```javascript
rivets.formatters.args = function(callback) {
	var args = Array.prototype.splice.call(arguments, 1);
	return function() {
  	return callback.apply(this, args);
  }
}
```

See here https://jsfiddle.net/jccazeaux/81hj1m00/8/

To help understanding difference between `call` and `args`, consider this 
```html
{ model.myFunction | call 'foo' model.bar }
```
Will be the same as
```html
{ model.myFunction | args 'foo' model.bar | call}
```

**Comment by Duder-onomy** [comment]
@erdalkaraca Does @jccazeaux  answer help you? In my opinion, it is pretty much exactly what you were trying to do. 

Can you let us know if you have any other questions? If not, can you close this? 
Thanks.

**Comment by erdalkaraca** [comment]
No, no other questions. Both answers help me better understand rivets. Thanks!
