### ISSUE TITLE
Same object in multple binds

### ISSUE THREAD

**Issue by olitomas** [mikeric/rivets#673]
I realise that this is probably not possible since rivets converts the binded object to something rivets specific (that has getters and setters for example). But I wanted to ask if anyone has found a way to achieve something like this or if its even possible without doing something too hacky:

`var obj = {
    goal: 'Be a loser'
};

var bind1 = rivets.bind($('#bind1'), {
  goal: obj.goal
});

var bind2 = rivets.bind($('#bind2'), {
  goal: obj.goal
});

obj.goal = 'Win at life';`

P.s. For those interested this can be achieved with "Watchjs" and a tiny bit more code. But I would prefer to achieve this without something like that.

**Comment by Duder-onomy** [comment]
@olitomas This is totally possible. Not sure why you would think it was not possible?

Fortunately, you are completely wrong.  

Here it is  https://jsfiddle.net/Vornagreg/oe29vaop/

We do this ALL the time. For example, if you has an application state singleton and wanted MANY sub views to be informed of changes in this state. Just bind them all to the same application state model.

Closing this since I don't want anyone accidentally reading this and thinking that this is not possible.

**Comment by olitomas** [comment]
Awesome thanks so much @Duder-onomy ....I was having troubles when binding like this in a fairly complex setup and did not manage to get things working. I wrongly assumed this was the issue, but obviously I was looking in the wrong direction.

**Comment by Duder-onomy** [comment]
Right on. Thanks for reaching out either way. If you figure out why yours is not working, feel free to bug me more. Helping strangers is the best part of my day.
