### ISSUE TITLE
Rivets not working with handlebar

### ISSUE THREAD

**Issue by rtUsmanKhan** [mikeric/rivets#675]
I am trying to send data from js using rivets but handlebar display it empty.
Does it work or not?

**Comment by Duder-onomy** [comment]
@rtUsmanKhan Rivets is working fine. 

Can you provide a non working jsfiddle so we can help you? 

If you have bound rivets correctly, then it should show up. 
If you look through the docs it should help you, especially with getting it up and running. Or if you look at old closed issues, there are TONS of cool examples to pull from. 

I am going to close this as it is not an issue. Please comment if you need more help.

**Comment by rtUsmanKhan** [comment]
I am very thankful to you for your response.
This is the url of my non-working jsfiddle.
[https://jsfiddle.net/3j6yLL02/](url)

**Comment by Duder-onomy** [comment]
Hi @rtUsmanKhan I am happy to help. 

There are 2 things in your fiddle you need to fix. 
* I could not find rivets installed into the fiddle. That is done on the left panel. I usually copy and past the rivets `dist` url into `rawgit` then past that development result into the libraries field in the left menu of jsfiddle.
* To use the `{{ thing.name }}` syntax, you will need to configure the template delimiters. 
By default, rivets will let you do `{ thing.name }` with one curly brace. If you want to use 2 curly braces, you need to configure rivets before you bind. 

How to use `{{` as template delimiters:
```javascript
  rivets.configure({
  	templateDelimiters : ['{{', '}}']
  });
```

Here is a working fork of your fiddle: https://jsfiddle.net/Vornagreg/eLvm5896/3/

I am going to change the name of this issue so that if people find it by googling they will get good results. 

Let me know if that helps.

**Comment by rtUsmanKhan** [comment]
Bundles of Thanks for your response.

It is working absolutely fine in jsfiddle (after including rivets.bundled.min.js).
In my actual working context (sugar crm) it is not working, i have included that external resource file there as well.

**Comment by Duder-onomy** [comment]
@rtUsmanKhan I cannot help you debug this issue with your implementation any further unless you demonstrate a case where it is not working. I believe you that it might not be working in Sugar CRM but I cannot help you fix your implementation if I cannot see it. Sorry.

**Comment by rtUsmanKhan** [comment]
Thanks to you.
It is working now as you described me.
